version: '3'
services:
  app:
    image: kickstart-backend
    container_name: kickstart-backend
    ports:
      - '6001:6001'
    environment:
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - DB_HOST=host.docker.internal
      - STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY