version: '3'
services:
  app:
    image: kickstart_backend
    container_name: kickstart_backend
    ports:
      - '6000:6000'
    environment:
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - DB_HOST=host.docker.internal